events {}
http {
  upstream limiter {
    server limiter-1:8080 max_fails=2 fail_timeout=5s;
    server limiter-2:8080 max_fails=2 fail_timeout=5s;
  }
  server {
    listen 80;
    location / {
      proxy_pass http://limiter;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
  }
}
